### ISSUE TITLE
Project does not contain binary code

### ISSUE THREAD

**Issue by boddulavineela** [SoftwareEngineeringToolDemos/ICSE-12-javamop#2]

**Comment by anshitasayal** [comment]
@boddulavineela The Binary code is available in the repository. Could you please elaborate on why the issue was created ?

**Comment by anshitasayal** [comment]
Here is the link to all the binaries in the repository : 

https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-javamop/tree/master/bin

**Comment by boddulavineela** [comment]
Sorry for the confusion. I am closing this issue as we have binaries.
